### PR TITLE
Create d8rules.json

### PR DESCRIPTION
**Pull request by dasjo**
Hey, would be great to have a d8rules board, thanks :)

btw. is there a way to pre-define filters? e.g. we use the contributor tag for issues which are open for anyone to contribute to...

greetings,
dasjo

### CODE REVIEW

**Comment by mglaman** [comment]
If you add the term ID in "tags" it'll filter by that. Example.. Check the Panopoly and Commerce json files, they filter on "sprint" tag.

Out doing a few Christmas things :) but can work on this tomorrow. Need to do a few clean up things still post-move to MEAN stack.

**Comment by dasjo** [comment]
Ok thanks! I think "tags" works fine, if you like to filter the whole board, e.g. commerce & panopoly filter all the issues by the same tag.

I was more looking for an option to expose an additional filter that can be used similar to branch, prio & category filters on the board.

But no worries, the board will also be of great help without the filter :)

**Comment by mglaman** [comment]
Oh, re-reading at desktop I get what you mean. Providing a set of tags that could be filtered on the board. I like that enhancement,

**Comment by mglaman** [comment]
@dasjo https://contribkanban.com/board/d8rules

**Pull request merged**
